### ISSUE TITLE
Schema-tizing with OERSchema

### ISSUE THREAD

**Issue by michael-collins** [hibbitts-design/grav-skeleton-oer-content-space#1]
Liking this project. Let's try adding a tiny bit of metadata to tell the internet that this course is an OER resource so it can show up in search engines more reliably. There are schema for all sorts of things including licensing individual parts of content, but that's for another time.

To start, in the main template, you can wrap content or the entire interface with the name of the OER course. Obviously you'd want to have theme variables driving the metadata attributes.  The template would look something like`resource="#{{ courseID.variable }}"` and `<meta property="oer:courseIdentifier" content="{{ coursename.variable }}">`

```
<body prefix="oer: http://oerschema.org/">
   <div resource="#COURSENAME101" typeof="oer:Course">
   <meta property="oer:courseIdentifier" content="CourseName 101">

     /// The Grav OER website. 

   </div>
</body>
```

To check that it's working, paste the published url in this tool and see if it pulls the course name: https://search.google.com/structured-data/testing-tool/u/0/

Here is an example with my own draft course materials: https://search.google.com/structured-data/testing-tool/u/0/#url=https%3A%2F%2Fdmd-program.gitbooks.io%2Fdmd-100-sp17%2Fcontent%2F

**Comment by michael-collins** [comment]
Not super familiar with how Grav stitches things together. Would there need to be a new theme to do this?

**Comment by paulhibbitts** [comment]
Thanks for the suggestion @michael-collins , let me look into this a bit and see what our options are. Ideally, I'd like to try to do this as a Page 'Atom' which would theme independent like 'Particles' are. More info about 'Atoms' here: http://docs.gantry.org/gantry5/configure/page-settings#atoms

**Comment by paulhibbitts** [comment]
@michael-collins I've been working on a possible prototype to support OERSchema in any Gantry theme using a custom 'Atom'. Here is a mockup config dialog, what do you think?

![2017-02-17_09-31-18](https://cloud.githubusercontent.com/assets/1812771/23076090/de213c66-f4f3-11e6-8160-233d936e0526.png)

Thanks,
Paul

**Comment by michael-collins** [comment]
Wow, this is coming along nicely. A license field will be one of the most powerful features of this. 

If we take a look at [Learning Component](http://oerschema.org/LearningComponent/), we can see that it will be describing if it is **for** or **has** other resources. This is how we'll be linking content together with the schema. The nice thing about it is, you can display it any way you want on a page, but under the hood the relationships are in tact.

In the longer term, we may need a slightly more intelligent tool that can pull data into a field to choose from as you create resources. So, if you create a learning component, you could then add it to an instructional pattern (Lesson 3: Making Stuff). Obviously many more options to be incorporated, but let's keep it simple for now. This is a great start.

**Comment by paulhibbitts** [comment]
Thanks for the feedback. The best approach is still evolving in my mind... it might also be Grav Shortcodes (https://github.com/getgrav/grav-plugin-shortcode-core), which then smaller chunks of content might be indicated for the schema. As a learning exercise, I will continue with the Gantry Atom approach and keep you posted on progress.

I also am wondering about the relationship between this and my current Creative Commons License Particle (https://github.com/hibbitts-design/grav-gantry5-particle-cc-license)... might this be part of that, or perhaps they are best separate at this point?

**Comment by michael-collins** [comment]
Hmm, your URL is not working in the seed tool for some reason: http://seed.oerschema.org/ There must be something that's not quite right.

We built this mini app to see if we could make modular parts. Try pasting in my URL: `https://open-curriculum.gitbooks.io/oer-schema-test/content/the_bauhaus.html` and clicking on the + button. You'll see it extract schematized parts from the content.

**Comment by paulhibbitts** [comment]
Thanks, I will try to figure out the issue with seed tool next.

**Comment by michael-collins** [comment]
@paulhibbitts You might be missing the vocab property.

```
<!-- http://example.com/my-course.html -->
<body vocab="http://oerschema.org" prefix="schema:http://schema.org/">
    <div typeof="Course">
        <h2 property="courseIdentifier">My Course</h2>
        <p property="description">A description of my course.</p>
        <img src="/path/to/my/image.jpg" property="schema:image">
        <!-- ... -->
    </div>
</body>
```

**Comment by paulhibbitts** [comment]
Thanks for the heads-up about the vocab tag. I've added it and still no luck but the Google tool results look better now...

http://sandbox.hibbittsdesign.org/grav-oer-content-space/

https://search.google.com/structured-data/testing-tool/u/0/#url=http%3A%2F%2Fsandbox.hibbittsdesign.org%2Fgrav-oer-content-space%2F

**Comment by michael-collins** [comment]
Hopefully [@curiosity26](https://github.com/curiosity26) will stop by this issue to take a look. I posted a link to this thread in our slack group.

**Comment by paulhibbitts** [comment]
@michael-collins Hi Michael, just thought I would follow-up to see if you've got any more leads about why the OER schema is not quite working on my prototype yet?

Once we get this working I can include an experimental version in my Grav Gantry skeleton for further exploration.

Thanks very much,
Paul

**Comment by michael-collins** [comment]
@paulhibbitts Looking into it today. Will let you know if I find anything.

**Comment by michael-collins** [comment]
Actually, if I remember correctly, the seed tool isn't designed to ingest course resources. Wondering if you applied the schema to an image or text, if it would come through.

**Comment by michael-collins** [comment]
Either way, it's more important that it works in the google Structured Data Testing tool, which it appears to be doing.

**Comment by michael-collins** [comment]
@paulhibbitts 

From Alex via email:

> So to fix your code here, it's super simple. RDF is case sensitive. So change oer:course to oer:Course. Also beware of using rel attributes. These are schema markup attributes that say the link or resource is related to another resource. So here it's trying to relate the element with a resource "home" which it thinks is part of the OER schema since that's the default vocabulary.

**Comment by paulhibbitts** [comment]
@michael-collins Thanks very much! So point #1 crystal clear (and done) but not sure if I need to act upon point #2?

My updated HTML markup is:
`<div resource="#OERCOURSE101" typeof="oer:Course">
  <meta property="oer:courseIdentifier" content="OER Course 101">`

However, the http://seed.oerschema.org/ tool still does not seem to give the a-ok for bhttp://sandbox.hibbittsdesign.org/grav-oer-content-space/ ... is there something else I need to do?

Thanks very much,
Paul

**Comment by michael-collins** [comment]
The SEED tool was never completed and only renders a limited type of resources (image, title, description), so don't worry about that not working. If it's working in google's test tool, you are set.

Regarding Alex's comment about rel links:

> ... beware of using rel attributes. These are schema markup attributes that say the link or resource is related to another resource. So here it's trying to relate the element with a resource "home" which it thinks is part of the OER schema since that's the default vocabulary. 

<img width="1225" alt="screen shot 2017-02-25 at 7 56 23 pm" src="https://cloud.githubusercontent.com/assets/1085304/23336134/9a471bb2-fb94-11e6-86a0-825128cf41d1.png">

Do you need to include `rel="home"` on that link?

**Comment by paulhibbitts** [comment]
Ah, a-ok then so I think I and ready to include this 'experimental' particle in my next OER content space skeleton.

Thanks for clarifying the 'rel' comment, that is generated by Gantry right now so not sure if I can control that.

I've been doing a bit of work on a possible Grav skeleton for a 'blog eportfolio' - nothing fancy but the idea is to give students a starter theme which keeps content separate from presentation and is Git Sync ready. As well, being based on Gantry and Gantry theme will work. I will update you on this soon.

Cheers,
Paul

**Comment by michael-collins** [comment]
Okay, I believe that you can remove `vocab="http://oerschema.org"` from the body and it will still work, but not throw unspecified type error. Just keep `prefix="oer: http://oerschema.org/"` in there.

**Comment by paulhibbitts** [comment]
@michael-collins Good news, just released a new version of the OER Content Space skeleton with the preliminary support of OER Schema that we've been discussing🙂 https://getgrav.org/downloads/skeletons I also added a bit of info about OER Schema on the 'Setup Guide' page of the skeleton.

Thanks for all your help!
