### ISSUE TITLE
No "Git Repository Tree URL" at step 4.2 of instructions

### ISSUE THREAD

**Issue by mcoster** [hibbitts-design/grav-skeleton-oer-content-space#2]
Hi, I really like your Project! I am partway through setting up a new site. I got to step 4.2 in [your instructions](http://learn.hibbittsdesign.org/coursehub/edit-with-git-config), but there us no "Git Repository Tree URL" on the "Configuration - Site" page. Have I done something wrong?

**Comment by paulhibbitts** [comment]
Hi @mcoster , glad you got things going! BTW, this is the OER Content Space project and you refer to the Open Course Hu instructions, that might be the issue?

BTW, I am working on a customized version of the standard Grav Theme Antimatter to bring a lot of the OER Content Space over to a standard Grav theme (Gantry not required): https://github.com/hibbitts-design/grav-theme-antimatter-open-publishing

**Comment by mcoster** [comment]
Thanks for the quick reply, Paul. Yes, I initially didn't understand that the OER Content Space and Open Course Hub were different things! Thanks for pointing out your customized Grav Theme Antimatter - looks good!
